### ISSUE TITLE
New feature?

### ISSUE THREAD

**Issue by kolmercm** [Brettanda/friday-bot#394]
A cool new feature I thought of that would involve two more "/" commands
-/pfp to change the profile picture of "Friday" Bot
-/name to change the name of the "Friday" Bot

I feel this would get more users for the Friday Bot. Either way it is a great bot, I admire your work so far
-Conor

**Comment by Brettanda** [comment]
> `/pfp`

I guess you mean how nitro users can change their PFP per server. Sadly this isn't possible yet AFAIK, but I think more profile customizations for bots are planned by Discord.

> `/name`

Yeah, that's something that I could add, but the way that Friday currently see's its name is just the nickname of the bot on a server, so I'm not sure it's necessary. What do you think?

Thanks, I'm really glad that people like Friday!

**Comment by kolmercm** [comment]
Thanks, changed the nickname. Hopefully in time we will be able to change bot pfps in discord and this will become possible.

**Comment by Brettanda** [comment]
No problem, When/if that feature gets released, that is definitely something I'm going to add.

**Comment by Brettanda** [comment]
@kolmercm I was suggested a really cool idea for how I can implement the profile picture feature, through webhooks. This is currently live and with a current setup chat channel you can use `!chatchannel webhook true`

**Comment by kolmercm** [comment]
Yo, good stuff! I will definitely see what I can do with this. Thanks so much for your work and time 💪🏻
